### ISSUE TITLE
MySQL credentials in source file

### ISSUE THREAD

**Issue by ParallelDiv** [pranshu0210/rest-api-iste-workshop#1]
You should not keep any user specific information like Database credentials or API keys in the source code. The issue is not severe for projects that you host locally, but in case you use cloud services like AWS, keeping API keys in the source code will allow other people to see and use them.

A preferable solution is to keep the credentials in a separate file or set them as environment variables. In case you store them in a file, keep that file outside of Git's version control by adding it to .gitignore. For Python, JSON files are suitable since Python will directly read them to a Python dictionary object.

**Comment by pranshu0210** [comment]
Thanks for pointing out the issue. It has now been resolved.
